spring:
  cloud:
    gateway:
      routes:
      - id: microservicio-product
        uri: lb://microservicio-product
        predicates:
        - Path=/api/products/**
        filters:
        - StripPrefix=2
        - name: SampleCookie
          args: 
            name: user
            value: Juan
            message: Mensaje personalizado para productos.
      - id: microservicio-items
        uri: lb://microservicio-items
        predicates:
        - Path=/api/items/**
        filters:
        - StripPrefix=2