resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      products:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 4s
    instances:
      products:
        base-config: defecto

spring:
  cloud:
    gateway:
      routes:
      - id: microservicio-product
        uri: lb://microservicio-product
        predicates:
        - Path=/api/products/**
        # - Header=token, 12345
        # - Method=GET, POST
        # - Query=color
        # - Cookie=color, azul
        # - Header=Content-Type, application/json
        filters:
        - name: CircuitBreaker
          args:
            name: products
            statusCodes: 500
            fallbackUri: forward:/api/items
        - StripPrefix=2
        - name: SampleCookie
          args: 
            name: user
            value: Juan
            message: Mensaje personalizado para productos.
      - id: microservicio-items
        uri: lb://microservicio-items
        predicates:
        - Path=/api/items/**
        filters:
        - StripPrefix=2
        - AddRequestHeader=token-request, nmasjasjma
        - AddResponseHeader=token-response, as123123123
        - AddRequestParameter=name, Juan
        - SetResponseHeader=Content-type, text/plain